### ISSUE TITLE
Disabling Reporting Features

### ISSUE THREAD

**Issue by RKNF404** [secureblue/hardened-chromium#10]
[`Reporting`](https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/cpp/features.cc;l=44) and [`CrashReporting`](https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_features.cc;l=226)

**Comment by qoijjj** [comment]
I *think* these are all covered by https://github.com/secureblue/hardened-chromium/blob/master/patches/disable-metrics-reporting.patch

but I'm not sure

**Comment by qoijjj** [comment]
we can just set enable_reporting=false in args in the spec patch

**Comment by qoijjj** [comment]
enable_reporting is set to false now https://github.com/secureblue/hardened-chromium/blob/master/hardening.patch#L271

@RKNF404 do you know if there's a reason why Vanadium doesn't change Reporting/CrashReporting?

**Comment by qoijjj** [comment]
Can't hurt to ask. They might be able to point us to the right code faster than we can find it, or we might be highlighting a gap. Either way it's a plus :smile:

**Comment by qoijjj** [comment]
@RKNF404 thanks for looking into this

**Comment by qoijjj** [comment]
@RKNF404 this line can be reverted I think 

https://github.com/secureblue/hardened-chromium/blob/master/patches/enable-audio-service-sandbox.patch#L19

reopening this to remind myself to do that
