### ISSUE TITLE
[FEAT] Add a subresource filter settings page like Brave

### ISSUE THREAD

**Issue by kreativK** [secureblue/hardened-chromium#103]
Add a page in the settings where users can search for, toggle, add custom filter lists and create custom filters just like in Brave. This would make it possible for users to customise the content filtering to their own liking and needs. It would also make it possible to block certain elements which may not already be in any of the provided subresource filter lists.

Would this be possible or is it out of the projects scope? Alternatively, would it affect privacy/security too much, e.g. by making fingerprinting easier?

![Image](https://github.com/user-attachments/assets/b7e3ea5e-7bf4-46dc-a6b8-806f4d5ed89e)

**Comment by RoyalOughtness** [comment]
> Alternatively, we could add a guide on how to add filters manually. But this isn't ideal. Especially since this would be overridden

@kreativK i will say that if there are filters you want to add, you can PR them in :smile:

**Comment by kreativK** [comment]
@RKNF404 Alright that is logical, thanks for the well written answer!


> [@kreativK](https://github.com/kreativK) i will say that if there are filters you want to add, you can PR them in 😄

Will do, thx 👍
