### ISSUE TITLE
[question] basic auth

### ISSUE THREAD

**Issue by drscream** [secureblue/hardened-chromium#146]
It looks like Basic Auth is not supported by hardened-chromium. Is there any possibly to turn it on again, because lot's of "internal" pages still uses basic auth.

**Comment by RoyalOughtness** [comment]
You should be able to override it via a policy json file you create in `/etc/chromium/policies/managed/`

https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::AuthSchemes
