### ISSUE TITLE
Reduce Cross-Site Leaks (Referrer and Window.Name)

### ISSUE THREAD

**Issue by RKNF404** [secureblue/hardened-chromium#21]
These should idealy be reduced and cleared respectively for privacy reasons.

**Comment by qoijjj** [comment]
makes sense, for the window.name, I assume this is something we can send to vanadium too?

and for referrers, the vanadium "reduce referrer setting" you're referring to is this patch, right? https://github.com/GrapheneOS/Vanadium/blob/b727d26b095a8383a81162951144d561c4c73e5b/patches/0114-make-cross-origin-referrer-behavior-configurable.patch#L267

**Comment by qoijjj** [comment]
@RKNF404 can this be closed?

**Comment by qoijjj** [comment]
oh right, yeah I'll leave this open then
