### ISSUE TITLE
disable various ai features by default

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/hardened-chromium#7]
https://source.chromium.org/chromium/chromium/src/+/main:components/compose/core/browser/compose_features.cc;l=13?q=kEnableCompose%20lang:cc&ss=chromium%2Fchromium%2Fsrc

**Comment by qoijjj** [comment]
@RKNF404 I think that code is referring to an optimization guide *for* compose, but I'm not sure. I don't think optimization hints/guides on their own are a bad thing, they improve performance.

https://go.dev/solutions/google/chrome

**Comment by qoijjj** [comment]
@RKNF404 I see, I'll look into this further in a bit. Even if that's the case though, I'm not sure that justifies removing optimizationguides altogether

**Comment by qoijjj** [comment]
@RKNF404 it depends on the implementation. if it's using pretrained models locally to do performance optimizations, there would be no downside. I'll need to look into this further

**Comment by qoijjj** [comment]
@RKNF404 I've been looking into this more. It looks like optimization guides are integrated with compose, but compose doesn't depend on them. It's a soft dependency:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/compose/compose_enabling.cc;l=138?q=kEnableCompose%20lang:cc&ss=chromium%2Fchromium%2Fsrc

If there is no optimization guide found, then COMPOSE_HINT_DECISION_UNSPECIFIED is returned, whereas COMPOSE_HINT_DECISION_COMPOSE_DISABLED disables compose.

so these would need to be disabled independently.

**Comment by qoijjj** [comment]
Please let me know if I'm reading that wrong though

**Comment by qoijjj** [comment]
this makes sense though because optimization guides are about page load optimizations, whereas compose is a context menu feature to do content generation

**Comment by qoijjj** [comment]
copying some additional options to look at that @RKNF404 mentioned in discord:

"CreateThemesSettings": 2, "DevToolsGenAiSettings": 2, "GoogleSearchSidePanelEnabled": false, "HelpMeWriteSettings": 2, "TabOrganizerSettings": 2,,

**Comment by qoijjj** [comment]
for kGoogleSearchSidePanelEnabled, the policy is set to true by default. However, the functionality doesn't show up for me (when I select text, right click, and search with google, it opens in a new tab).

So I dug a bit more. the policy gets checked here:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/side_panel/companion/companion_utils.cc;l=69;bpv=1;bpt=1?q=kGoogleSearchSidePanelEnabled%20lang:cc&ss=chromium%2Fchromium%2Fsrc&start=11

and that function is used here:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/side_panel/companion/companion_utils.cc;l=121?q=GoogleSearchSidePanelEnabled%20lang:cc&ss=chromium%2Fchromium%2Fsrc&start=1

but call function isn't reached if the companion feature is disabled:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/side_panel/companion/companion_utils.cc;l=93;drc=5203366d4cf174b9331ee33563e0520f10b60828

and the companion feature is disabled when GOOGLE_CHROME_BRANDING is false

So, at least for this policy no action is needed.

**Comment by qoijjj** [comment]
For HelpMeWriteSettings, the policy is mapped to kComposeEnterprisePolicyAllowed:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/policy/configuration_policy_handler_list_factory.cc;l=2214?q=HelpMeWriteSettings%20lang:cc&ss=chromium%2Fchromium%2Fsrc&start=21

which is enabled by default here:

**Comment by qoijjj** [comment]
same for:

{ key::kCreateThemesSettings,
    optimization_guide::model_execution::prefs::[kWallpaperSearchEnterprisePolicyAllowed](https://source.chromium.org/chromium/chromium/src/+/main:components/optimization_guide/core/model_execution/model_execution_prefs.cc;drc=5203366d4cf174b9331ee33563e0520f10b60828;l=22),

{ key::kTabOrganizerSettings,
    optimization_guide::model_execution::prefs::[kTabOrganizationEnterprisePolicyAllowed](https://source.chromium.org/chromium/chromium/src/+/main:components/optimization_guide/core/model_execution/model_execution_prefs.cc;drc=5203366d4cf174b9331ee33563e0520f10b60828;l=15),
    base::[Value](https://source.chromium.org/chromium/chromium/src/+/main:base/values.h;drc=5203366d4cf174b9331ee33563e0520f10b60828;l=150)::[Type](https://source.chromium.org/chromium/chromium/src/+/main:base/values.h;drc=5203366d4cf174b9331ee33563e0520f10b60828;l=157)::[INTEGER](https://source.chromium.org/chromium/chromium/src/+/main:base/values.h;drc=5203366d4cf174b9331ee33563e0520f10b60828;l=160)},

**Comment by qoijjj** [comment]
for devtools it's set to allowwithoutlogging here:

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/devtools/aida_client.cc;l=139?q=kDevToolsGenAiSettings%20lang:cc&ss=chromium%2Fchromium%2Fsrc&start=11

**Comment by qoijjj** [comment]
https://github.com/secureblue/hardened-chromium/pull/41

leaving this issue open because there are additional ai features getting added to upstream

**Comment by RoyalOughtness** [comment]
completed awhile ago
