### ISSUE TITLE
PDF file handling

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/hardened-chromium#73]
I can see that hardened-chromium opts in to opening PDF files externally.

https://github.com/secureblue/hardened-chromium/blob/9a196934f237232b383206b874cb9e52f952a460/patches/set-default-always-open-pdf-externally.patch#L10

[PDF.js](https://github.com/mozilla/pdf.js) seems more secure and more convenient than external readers, because it has all of the sandboxing guarantees of V8. And the attack surface is reduced because it means relying on less C++ code (either inside or outside the browser)

Could probably strip pdfium from the build entirely.

Firefox and Brave have chosen this approach as the default for that reason.

Interested in getting the stance documented, in any event.

**Comment by qoijjj** [comment]
> Interested in getting the stance documented, in any event.

The logic is that it's preferable to open pdfs in an independent environment, away from the browser. Preferably, in a maximally sandboxed pdf viewer. For example https://flathub.org/apps/org.gnome.Papers

Setting the default to open pdfs externally does the bare minimum, that being that by default the browser won't render PDFs.

> [PDF.js](https://github.com/mozilla/pdf.js) seems more secure and more convenient than external readers, because it has all of the sandboxing guarantees of V8. And the attack surface is reduced because it means relying on less C++ code (either inside or outside the browser)

It also opens up all the attack surface of V8 for pdf rendering.

**Comment by qoijjj** [comment]
> I wouldn't call any flatpak maximally sandboxed,

whoops yeah I wrote that really poorly. The ideal would be to maximally sandbox it. In practice a sandbox is not that

> Let me know what your opinion on this, but I think this should be reconsidered.

If you mean the default external pdf setting, then yeah I agree. I think it's one of the more dubious changes.

If you mean subbing pdfium for pdf.js, I'm not convinced of the value add
