### ISSUE TITLE
Cannot open preinstalled hardened chromium in secure blue

### ISSUE THREAD

**Issue by Cicindis** [secureblue/hardened-chromium#88]
I cannot open hardened-chromium neither from the apps or from the command line.

```
flatpak run org.chromium.Chromium
error: app/org.chromium.Chromium/x86_64/master not installed

```
It doesn't show in FlatSeal either but the Chromium Web Browser app does appear.

**Comment by Cicindis** [comment]
It worked! Thank you

**Comment by qoijjj** [comment]
@Cicindis great, but you shouldn't need to run from the command line. It sounds like you previously or currently have a chromium flatpak desktop file installed.

**Comment by Cicindis** [comment]
I did install one when I started getting the error, but after I deleted it with the app settings & data from the Software app the same issue kept happening. The error started happening after I installed emacs with rpm-ostree and restarted my computer. I have to run the command `rm ~/.config/chromium/Singleton*` when restarting my computer to use hardened-chromium.

**Comment by qoijjj** [comment]
@Cicindis If you are on an nvidia image with an nvidia optimus laptop, then you almost certainly just need to run this:

https://github.com/secureblue/secureblue/blob/live/FAQ.md#why-arent-my-apps-loading-on-nvidia-optimus
