### ISSUE TITLE
Disable TPCD Bypasses

### ISSUE THREAD

**Issue by RKNF404** [secureblue/hardened-chromium#9]
[`TpcdMetadataGrants`](https://source.chromium.org/chromium/chromium/src/+/main:net/base/features.cc;l=250;bpv=0;bpt=1) and [`TpcdHeuristicsGrants`](https://source.chromium.org/chromium/chromium/src/+/main:components/content_settings/core/common/features.cc;l=101). Basically the same feature.

**Comment by qoijjj** [comment]
Is there a reason Vanadium doesn't do this too? We should cut issues to both projects for issues that are in scope for both so both projects can benefit

**Comment by qoijjj** [comment]
@RKNF404 We should take a similar approach about that. But it depends on how much risk the feature actually poses. We can do a risk analysis on a case by case basis.

**Comment by qoijjj** [comment]
@RKNF404 It's that and also that the more patches we add, the more maintenance burden there is. 

> For now at least we can afford to be a little risky.

I think we should start with good habits now so this can be ready to go out to secureblue soon.

**Comment by qoijjj** [comment]
Thanks for investigating this

**Comment by qoijjj** [comment]
please reopen if upstream changes things, like you mentioned
