### ISSUE TITLE
Misplaced window

### ISSUE THREAD

**Issue by kreativK** [secureblue/hardened-chromium#99]
The whole chromium window gets misplaced about half of the time when minimizing and maximizing the program. 

When this bug appears after minimizing chromium, the top bar gets placed over the top border of the screen and the program window gets cut in half.
![Image](https://github.com/user-attachments/assets/a6d43f5e-1b37-46a3-8267-66408165b886)

When it appears after maximizing chromium, there is a large gap above the top bar and all mouse clicks are misplaced. The mouse appears, the height of the gap over, where it actually clicks.
![Image](https://github.com/user-attachments/assets/f35bb078-509e-461d-9291-ad5fa488e57a)

The only way to fix it is to spam f11 until it changes back to normal, but this doesn't stop it from happening.

I'm using the kinoite-nvidia-userns-hardened image.

**Comment by RoyalOughtness** [comment]
This is almost certainly upstream, but it would be good to confirm. Can you layer google-chrome and see if it happens there too?

Chrome and Kwin-wayland have had windowing issues for years, especially on nvidia 😔

**Comment by kreativK** [comment]
> This is almost certainly upstream, but it would be good to confirm. Can you layer google-chrome and see if it happens there too (with the same flags)?

Yep, that sadly seems to be the case. The exact same thing happens with google-chrome

**Comment by RoyalOughtness** [comment]
@kreativK out of curiousity is this the x11 backend or the wayland backend? I seem to remember this being an xwayland issue

That said, I suspect switching to gnome would fix it, but that's probably not what you want to hear.

Closing as upstream :pensive:

**Comment by kreativK** [comment]
> [@kreativK](https://github.com/kreativK) out of curiousity is this the x11 backend or the wayland backend? I seem to remember this being an xwayland issue

x11 backend

> That said, I suspect switching to gnome would fix it, but that's probably not what you want to hear.

Yeah, might do that anyway in the future. Thanks👍
